<?php

namespace Magenest\MultipleWishlist\Block\Modal;

use Magento\Framework\App\Config\ScopeConfigInterface;
use Magento\Framework\View\Element\Template;

/**
 * Class Data
 * @package Magenest\MultipleWishlist\Block\Modal
 */
class Data extends Template
{
//    protected $_formKey;
    /**
     * @var \Magenest\MultipleWishlist\Model\MultipleWishlistFactory
     */
    protected $multipleWishlistFactory;

    public $scopeConfig;

    /**
     * Data constructor.
     * @param Template\Context $context
     * @param \Magenest\MultipleWishlist\Model\MultipleWishlistFactory $multipleWishlistFactory
     * @param array $data
     */
    public function __construct(
        Template\Context $context,
        \Magenest\MultipleWishlist\Model\MultipleWishlistFactory $multipleWishlistFactory,
        ScopeConfigInterface $scopeConfig,
//        \Magento\Framework\Data\Form\FormKey $formkey,
        array $data = []
    )
    {
        $this->multipleWishlistFactory = $multipleWishlistFactory;
        $this->scopeConfig = $scopeConfig;
//        $this->_formKey = $formkey;
        parent::__construct($context, $data);
    }

    /**
     * @return string
     */
    public function getBaseUrl()
    {
        return parent::getBaseUrl(); // TODO: Change the autogenerated stub
    }

    /**
     * @return array
     */
    public function getWishlist()
    {
        $return = array();
        $wishlist = $this->multipleWishlistFactory->create();
        $return = $wishlist->loadWishlist();
        return $return;
    }

    public function getCountWishlist()
    {
        $wishlistCount = $this->multipleWishlistFactory->create();
        $number = $wishlistCount->getCountWishlist();
        return $number;
    }
    /*
        public function defaultAddUrl()
        {
            return $this->_storeManager->getStore()->getBaseUrl().'wishlist/index/add/';
        }
        public function getFormKey()
        {
            return $this->_formKey->getFormKey();
        }
    */
}