<?php
/**
 * Wishlist item collection grouped by customer id
 */
namespace Magenest\MultipleWishlist\Model\ResourceModel\Item\Collection;

use Magento\Customer\Controller\RegistryConstants as RegistryConstants;

class Grid extends \Magenest\MultipleWishlist\Model\ResourceModel\Item\Collection
{
    public function _construct()
    {
        parent::_construct(); // TODO: Change the autogenerated stub
    }

    protected function _initSelect()
    {
        parent::_initSelect();
    }

}
