<?php
/**
 * @var $block \Magento\Wishlist\Block\Catalog\Product\View\AddTo\Wishlist
 */
?>
<!--<script>-->
<!--    require([-->
<!--        'Magenest_MultipleWishlist/js/add-to-wishlist'-->
<!--    ], function () {-->
<!--        'use strict';-->
<!--        return 0;-->
<!--    });-->
<!--</script>-->
<?php if ($block->isWishListAllowed()) : ?>
    <a href="#"
       class="action towishlist"
       data-post='<?php /* @escapeNotVerified */
       echo $block->getWishlistParams(); ?>'
       data-action="add-to-wishlist"><span><?php /* @escapeNotVerified */
            echo __('Add to Wish List') ?></span></a>
<?php endif; ?>
<script type="text/x-magento-init">
    {
        "body": {
            "addToWishlist": <?php /* @escapeNotVerified */ echo $block->getWishlistOptionsJson() ?>
        }
    }
</script>
