<?php

namespace Magenest\MultipleWishlist\Block\Adminhtml\Dashboard;

use Magento\Framework\View\Element\Template;

/**
 * Class Report
 * @package Magenest\MultipleWishlist\Block\Adminhtml\Dashboard
 */
class Report extends Template
{

    /**
     * @var \Magenest\MultipleWishlist\Model\ResourceModel\ReportWishlist\CollectionFactory
     */
    protected $reportCollectionFactory;
    /**
     * @var \Magento\Backend\Helper\Data
     */
    protected $helperBackend;

    /**
     * Report constructor.
     * @param Template\Context $context
     * @param \Magenest\MultipleWishlist\Model\ResourceModel\ReportWishlist\CollectionFactory $reportCollectionFactory
     * @param \Magento\Backend\Helper\Data $helperBackend
     * @param array $data
     */
    public function __construct(
        Template\Context $context,
        \Magenest\MultipleWishlist\Model\ResourceModel\ReportWishlist\CollectionFactory $reportCollectionFactory,
        \Magento\Backend\Helper\Data $helperBackend,
        array $data = []
    )
    {
        $this->reportCollectionFactory = $reportCollectionFactory;
        $this->helperBackend = $helperBackend;
        parent::__construct($context, $data);
    }

    /**
     * @return string
     */
    public function getAdminUrl()
    {
        return $this->helperBackend->getHomePageUrl();
    }

    /**
     * @return string
     */
    public function getBaseUrl()
    {
        return parent::getBaseUrl(); // TODO: Change the autogenerated stub
    }

    /**
     * @return array
     */
    public function getReportCollection()
    {
        $data = $this->reportCollectionFactory->create()->getData();
        return $data;
    }

    /**
     * @return int
     */
    public function getPercentCount()
    {
        $sum = 0;
        $data = $this->reportCollectionFactory->create()->getData();
        foreach ($data as $var):{
            $sum += $var['count'];
        }endforeach;
        return $sum;
    }
}